import random

QUESTIONS = {
    1: [
        ("Hvað er 1+1?", ["2"]),
        ("Hvað er 2+2?", ["4"]),
        ("Hvað er 3+3?", ["6"]),
        ("Hvað er 4+4?", ["8"]),
        ("Hvað er 5+5?", ["10"]),
        ("Hvað er 6+6?", ["12"]),
        ("Hvað er 7+7?", ["14"]),
        ("Hvað er 3+4?", ["7"]),
        ("Hvað er 8+2?", ["10"]),
        ("Hvað er 9+1?", ["10"]),
        ("Hvað er 10-3?", ["7"]),
        ("Hvað er 10-4?", ["6"]),
        ("Hvað er 8-5?", ["3"]),
        ("Hvað er 9-6?", ["3"]),
        ("Hvað er 2x3?", ["6"]),
        ("Hvað er 2x5?", ["10"]),
        ("Hvað er 3x4?", ["12"]),
        ("Hvað er 10/2?", ["5"]),
        ("Hvað er 12/3?", ["4"]),
        ("Hvað er 20/4?", ["5"]),
        ("Hvað heita afkvæmi hunda?", ["hvolpar"]),
        ("Hvað heita afkvæmi katta?", ["kettlingar"]),
        ("Hvað heita afkvæmi hesta?", ["folald"]),
        ("Hvað heita afkvæmi kúa?", ["kálfar"]),
        ("Hvað heita afkvæmi svína?", ["grísir"]),
        ("Hvað heita afkvæmi kindanna?", ["lömb"]),
        ("Hvaða dýr er hæst í heimi?", ["gíraffi"]),
        ("Hvaða dýr er stærst í heimi?", ["steypireyður"]),
        ("Hvaða dýr er stærst á landi?", ["fíll"]),
        ("Hvaða dýr er hraðast í heimi?", ["hlébarði"]),
        ("Hvað borðar pandabjörn?", ["bambus"]),
        ("Hvaða dýr sefur hangandi á kvisti?", ["leðurblaka"]),
        ("Hvaða dýr hefur skál á baki?", ["skjaldbaka"]),
        ("Hvaða dýr er kallaður konungur dýraríkisins?", ["ljón"]),
        ("Hvaða sjávardýr hefur átta arma?", ["kolkrabbi"]),
        ("Hvað heitir höfuðborg Íslands?", ["reykjavík"]),
        ("Hvað heitir höfuðborg Írlands?", ["dublin"]),
        ("Hvað heitir höfuðborg Frakklands?", ["paris"]),
        ("Hvað heitir höfuðborg Englands?", ["london"]),
        ("Hvað heitir höfuðborg Þýskalands?", ["berlin"]),
        ("Hvað heitir höfuðborg Ítalíu?", ["róm"]),
        ("Hvað heitir höfuðborg Spánar?", ["madrid"]),
        ("Hvað heitir höfuðborg Danmerkur?", ["kaupmannahöfn"]),
        ("Hvað heitir höfuðborg Noregs?", ["osló"]),
        ("Hvað heitir höfuðborg Svíþjóðar?", ["stokkhólmur"]),
        ("Hvað heitir stærsta land í heimi?", ["rússland"]),
        ("Hvað heitir hæsti fjall í heimi?", ["everest"]),
        ("Á hvaða meginlandi er Egyptaland?", ["afríka"]),
        ("Hvenær fengu Bandaríkin sjálfstæði?", ["1776"]),
        ("Hvað heitir lengsti fljót í heimi?", ["níl"]),
        ("Hvaða reikistjarna er næst sólinni?", ["merkúr", "merkúríus"]),
        ("Hvaða reikistjarna er við hliðina á jörðinni?", ["mars"]),
        ("Hvað heitir tungl jarðarinnar?", ["tunglið", "tungl"]),
        ("Hversu margar reikistjörnur eru í sólkerfinu?", ["8"]),
        ("Hvaða litur kemur fyrst í regnboga?", ["rauður"]),
        ("Hversu margar litir eru í regnboga?", ["7"]),
        ("Hvað heitir vatn þegar það er gufað upp?", ["gufa"]),
        ("Hvað heitir fryst vatn?", ["ís"]),
        ("Hversu margir leikmenn eru í fótboltaliði?", ["11"]),
        ("Hversu margir leikmenn eru í körfuboltaliði?", ["5"]),
        ("Hversu margir leikmenn eru í handknattleiksliði?", ["7"]),
        ("Hversu oft eru ólympíuleikarnir haldnir?", ["fjórum árum"]),
        ("Hvaða leikur er spilaður með kylfum og bolti á grasvelli?", ["golf"]),
        ("Hvað heitir stærsta pýramídi í Egyptalandi?", ["cheops"]),
        ("Hvenær varð Ísland lýðveldið?", ["1944"]),
        ("Hvenær byggðist Ísland?", ["874"]),
        ("Hvað heitir þingstaður Íslendinga?", ["þingvellir"]),
        ("Hvað heitir elsta þing í heimi?", ["alþingi"]),
        ("Hvenær hófst fyrri heimsstyrjöldin?", ["1914"]),
        ("Hvenær lauk seinni heimsstyrjöldinni?", ["1945"]),
        ("Hversu margar dagar eru í viku?", ["7"]),
        ("Hversu margar mánuðir eru í ári?", ["12"]),
        ("Hversu margar klukkustundir eru á dag?", ["24"]),
        ("Hversu margar mínútur eru í klukkustund?", ["60"]),
        ("Hvað heitir fyrsti mánuður ársins?", ["janúar"]),
        ("Hvað heitir síðasti mánuður ársins?", ["desember"]),
        ("Hvað heitir dagurinn á eftir mánudegi?", ["þriðjudagur"]),
        ("Hvað heitir dagurinn á eftir fimmtudegi?", ["föstudagur"]),
        ("Hvenær er jól?", ["25. desember"]),
        ("Hvenær er gamlárskvöld?", ["31. desember"]),
        ("Úr hvaða ávexti er vín gert?", ["vínber"]),
        ("Úr hvaða dýri kemur beikon?", ["svín"]),
        ("Hvað heitir japanski rétturinn með hrísgrjónum og fiski?", ["sushi"]),
        ("Hvaða ávöxtur er gulur og krókóttur?", ["banani"]),
        ("Hvaða grænmeti er appelsínugult og langt?", ["gulrót"]),
        ("Úr hvaða korni er brauð oftast bakað?", ["hveiti"]),
        ("Hvaða drykk er gerður úr appelsínum?", ["appelsínusafi"]),
        ("Hvað heitir uppfinning Alexanders Graham Bell?", ["sími"]),
        ("Hvenær fór maðurinn fyrst á tunglið?", ["1969"]),
        ("Hvað heitir fyrsti gervitungl jarðarinnar?", ["sputnik"]),
        ("Hvað heitir stærsta leitarvél netsins?", ["google"]),
        ("Hvaða fyrirtæki bjó til iPhone?", ["apple"]),
        ("Hvað er hundur á ensku?", ["dog"]),
        ("Hvað er köttur á ensku?", ["cat"]),
        ("Hvað er hestur á ensku?", ["horse"]),
        ("Hvað er fiskur á ensku?", ["fish"]),
        ("Hvað er rauður á ensku?", ["red"]),
        ("Hvað er blár á ensku?", ["blue"]),
        ("Hvað er gulur á ensku?", ["yellow"]),
        ("Hvað er grænn á ensku?", ["green"]),
        ("Hvað er svartur á ensku?", ["black"]),
        ("Hvað er vatn á ensku?", ["water"]),
    ],

    2: [
        ("Hvað heitir höfuðborg Portúgals?", ["Lissabon"]),
        ("Hvað heitir höfuðborg Grikklands?", ["Aþena"]),
        ("Hvað heitir höfuðborg Austurríkis?", ["Vín"]),
        ("Hvað heitir höfuðborg Hollands?", ["Amsterdam"]),
        ("Hvað heitir höfuðborg Belgíu?", ["Brussel"]),
        ("Hvað heitir höfuðborg Póllands?", ["Varsjá"]),
        ("Hvað heitir höfuðborg Tékklands?", ["Prag"]),
        ("Hvað heitir höfuðborg Ungverjalands?", ["Búdapest"]),
        ("Hvað heitir höfuðborg Rúmeníu?", ["Búkarest"]),
        ("Hvað heitir höfuðborg Indlands?", ["Nýdelhí"]),
        ("Hvað heitir höfuðborg Kína?", ["Peking"]),
        ("Hvað heitir höfuðborg Japans?", ["Tókýó"]),
        ("Hvað heitir höfuðborg Ástralíu?", ["Canberra"]),
        ("Hvað heitir höfuðborg Brasilíu?", ["Brasília"]),
        ("Hvað heitir höfuðborg Kanada?", ["Ottawa"]),
        ("Hvað heitir lengsti fljót í Evrópu?", ["Volga"]),
        ("Hvaða land er stærst í Evrópu að flatarmáli?", ["Rússland"]),
        ("Á hvaða meginlandi er Argentína?", ["Suður-Ameríka"]),
        ("Hvaða land á stærsta íbúatölu í heimi?", ["Indland"]),
        ("Hvaða haf liggur milli Evrópu og Ameríku?", ["Atlantshaf"]),
        ("Hvenær hófst seinni heimsstyrjöldin?", ["1939"]),
        ("Hvenær féll Berlínarmúrinn?", ["1989"]),
        ("Hvað hét forsetinn sem var myrtur í Dallas 1963?", ["Kennedy"]),
        ("Hvað hét skipið sem sökknaði 1912?", ["Titanic"]),
        ("Hvenær lauk fyrri heimsstyrjöldinni?", ["1918"]),
        ("Hvað hét leiðtogi Nasista í Þýskalandi?", ["Hitler"]),
        ("Hvenær uppgötvaði Kristófer Kólumbus Ameríku?", ["1492"]),
        ("Hvað hét fyrsti forseti Bandaríkjanna?", ["Washington"]),
        ("Hvaða ár var Franska byltingin?", ["1789"]),
        ("Hvað heitir næsta reikistjarna við sólina?", ["Merkúr", "Merkúríus"]),
        ("Hversu margar reikistjörnur eru í sólkerfinu?", ["8"]),
        ("Hvað heitir stærsta reikistjarna sólkerfisins?", ["Júpíter"]),
        ("Hvað er efnatákn vatns?", ["H2O"]),
        ("Hvað er efnatákn gullsins?", ["Au"]),
        ("Hversu margar bein eru í mannslíkamanum?", ["206"]),
        ("Hvað heitir efnið sem sólin er að mestu gerð úr?", ["vetni"]),
        ("Hvaða dýr er skyldust manni?", ["simpansi"]),
        ("Hvaða land vann heimsmeistara í fótbolta 2022?", ["Argentína"]),
        ("Hvaða land vann heimsmeistara í fótbolta 2018?", ["Frakkland"]),
        ("Hvað heitir stærsta fótboltaleikvangi í heimi?", ["Maracaná"]),
        ("Hversu margar leikir eru í NBA leiktíð?", ["82"]),
        ("Hvað heitir stærsta tennismót í heimi?", ["Wimbledon"]),
        ("Hvaða ár voru fyrstu nútíma ólympíuleikarnir?", ["1896"]),
        ("Hversu margar mínútur er fótboltaleikur?", ["90"]),
        ("Hvað hét hljómsveit Jóhns Lennons?", ["Beatles"]),
        ("Hvaða land er Elvis Presley frá?", ["Bandaríkin"]),
        ("Hvaða ár gaf Michael Jackson út Thriller?", ["1982"]),
        ("Hvað hét hljómsveit Freddie Mercury?", ["Queen"]),
        ("Hvaða land er ABBA frá?", ["Svíþjóð"]),
        ("Hvað heitir þekktasta málverk Leonardos da Vinci?", ["Mona Lisa"]),
        ("Hvaða land er Pablo Picasso frá?", ["Spánn"]),
        ("Hvað hét Shakespeare fyrsta nafni?", ["William"]),
        ("Hvaða bók er mest seld í sögu heimsins?", ["Biblían"]),
        ("Hvaða ár kom fyrsta Star Wars kvikmyndin út?", ["1977"]),
        ("Hvað hét prinsessan í Frozen?", ["Elsa"]),
        ("Hvaða land er anime upprunalega frá?", ["Japan"]),
        ("Hvað heitir þekktasta sjónvarpsþáttur um brotin hjón í New Mexico?", ["Breaking Bad"]),
        ("Hvað er 12 x 12?", ["144"]),
        ("Hvað er 15 x 15?", ["225"]),
        ("Hvað er 1000 / 8?", ["125"]),
        ("Hvað er ferningsrót af 144?", ["12"]),
        ("Hvað er ferningsrót af 81?", ["9"]),
        ("Hvað er 17 + 38?", ["55"]),
        ("Hvað er 25% af 200?", ["50"]),
        ("Hvað er 50% af 350?", ["175"]),
        ("Hvað er 7 x 8?", ["56"]),
        ("Hvað er 9 x 9?", ["81"]),
        ("Hvað er 144 / 12?", ["12"]),
        ("Hvað er 13 x 7?", ["91"]),
        ("Hvenær var Alþingi stofnað?", ["930"]),
        ("Hvað heitir stærsta eldfjall á Íslandi?", ["Hekla"]),
        ("Hvað heitir stærsta vatn á Íslandi?", ["Þingvallavatn"]),
        ("Hvað heitir stærsta jökull á Íslandi?", ["Vatnajökull"]),
        ("Hvenær kom Icesave deilumálið upp?", ["2008"]),
        ("Hvað heitir þjóðsöngur Íslands?", ["Lofsöngur"]),
        ("Hvenær gekk Ísland í NATO?", ["1949"]),
        ("Hvað heitir lengsta fljót á Íslandi?", ["Þjórsá"]),
    ],

    3: [
        ("Hvað heitir höfuðborg Finnlands?", ["Helsinki"]),
        ("Hvað heitir höfuðborg Íraks?", ["Bagdad"]),
        ("Hvað heitir höfuðborg Úkraínu?", ["Kýev"]),
        ("Hvað heitir höfuðborg Sviss?", ["Bern"]),
        ("Hvað heitir höfuðborg Króatíu?", ["Zagreb", "Sagreb"]),
        ("Hvað heitir höfuðborg Slóvakíu?", ["Bratislava"]),
        ("Hvað heitir höfuðborg Serbíu?", ["Belgrad"]),
        ("Hvað heitir höfuðborg Albaníu?", ["Tírana"]),
        ("Hvað heitir höfuðborg Búlgaríu?", ["Sofía"]),
        ("Hvað heitir höfuðborg Litháen?", ["Vilníus"]),
        ("Hvað heitir höfuðborg Eistlands?", ["Tallinn"]),
        ("Hvað heitir höfuðborg Lettlands?", ["Ríga"]),
        ("Hvað heitir höfuðborg Lúxemborgar?", ["Lúxemborg"]),
        ("Hvað heitir höfuðborg Makedóníu?", ["Skopje"]),
        ("Hvað heitir höfuðborg Moldóvu?", ["Kisínev"]),
        ("Hvað heitir höfuðborg Suður-Kóreu?", ["Seúl"]),
        ("Hvað heitir höfuðborg Norður-Kóreu?", ["Pjongjang"]),
        ("Hvað heitir höfuðborg Taílands?", ["Bangkok"]),
        ("Hvað heitir höfuðborg Víetnam?", ["Hanói"]),
        ("Hvað heitir höfuðborg Írans?", ["Teheran"]),
        ("Hvað heitir höfuðborg Pakistans?", ["Íslamabad"]),
        ("Hvað heitir höfuðborg Bangladess?", ["Dakka"]),
        ("Hvað heitir höfuðborg Mongolíu?", ["Úlan Bátar"]),
        ("Hvað heitir höfuðborg Afganistans?", ["Kabúl"]),
        ("Hvað heitir höfuðborg Myanmars?", ["Napjídá"]),
        ("Hvað heitir höfuðborg Kambódíu?", ["Phnom Penh"]),
        ("Hvað heitir höfuðborg Singapúr?", ["Singapúr"]),
        ("Hvað heitir höfuðborg Malasíu?", ["Kuala Lumpur"]),
        ("Hvað heitir höfuðborg Indónesíu?", ["Djakarta", "Jakarta"]),
        ("Hvað heitir höfuðborg Filippseyja?", ["Maníla"]),
        ("Hvað heitir höfuðborg Egyptalands?", ["Kaíró"]),
        ("Hvað heitir höfuðborg Nígeríu?", ["Abuja"]),
        ("Hvað heitir höfuðborg Kenýu?", ["Naíróbí"]),
        ("Hvað heitir höfuðborg Eþíópíu?", ["Addis Abeba"]),
        ("Hvað heitir höfuðborg Marokkó?", ["Rabat"]),
        ("Hvað heitir höfuðborg Suður-Afríku?", ["Pretoria"]),
        ("Hvað heitir höfuðborg Tansaníu?", ["Dodoma"]),
        ("Hvað heitir höfuðborg Gana?", ["Akkra"]),
        ("Hvað heitir höfuðborg Algeirslands?", ["Alger"]),
        ("Hvað heitir höfuðborg Angólu?", ["Lúanda"]),
        ("Hvað heitir höfuðborg Mexíkó?", ["Mexíkóborg"]),
        ("Hvað heitir höfuðborg Argentínu?", ["Buenos Aires"]),
        ("Hvað heitir höfuðborg Kólumbíu?", ["Bogotá"]),
        ("Hvað heitir höfuðborg Perú?", ["Lima"]),
        ("Hvað heitir höfuðborg Venesúela?", ["Karakas"]),
        ("Hvað heitir höfuðborg Kúbu?", ["Havana"]),
        ("Hvað heitir höfuðborg Chíle?", ["Santíagó"]),
        ("Hvað heitir höfuðborg Ekvador?", ["Kító"]),
        ("Hvað heitir höfuðborg Paragvæ?", ["Asunción"]),
        ("Hvað heitir höfuðborg Úrúgvæ?", ["Montevídeo"]),
        ("Hvað heitir lengsta fljót í Afríku?", ["Níl"]),
        ("Hvað heitir lengsta fljót í Suður-Ameríku?", ["Amazonas"]),
        ("Hvað heitir lengsta fljót í Asíu?", ["Jangtsé"]),
        ("Hvað heitir lengsta fljót í Evrópu?", ["Volga"]),
        ("Hvað heitir stærsta stöðuvatn í heimi?", ["Kaspíahaf"]),
        ("Hvað heitir stærsta ferskvatnsstöðuvatn í heimi?", ["Yfirvötn"]),
        ("Hvað heitir stærsta stöðuvatn í Afríku?", ["Viktoríuvatn"]),
        ("Hvað heitir dýpsta stöðuvatn í heimi?", ["Bajkal"]),
        ("Á hvaða meginlandi er Amazonas?", ["Suður-Ameríka"]),
        ("Hvað heitir hæsti fjall í Evrópu?", ["Mont Blanc"]),
        ("Hvað heitir hæsti fjall í Afríku?", ["Kilimanjaro"]),
        ("Hvað heitir hæsti fjall í Suður-Ameríku?", ["Aconcagua"]),
        ("Hvað heitir hæsti fjall í Norður-Ameríku?", ["Denali"]),
        ("Hvað heitir stærsta eyja í heimi?", ["Grænland"]),
        ("Hvað heitir stærsta eyja í Miðjarðarhafi?", ["Sikiley"]),
        ("Á hvaða heimsálfu er Kilimanjaro?", ["Afríka"]),
        ("Hvað heitir fjallgarðurinn á milli Evrópu og Asíu?", ["Úral"]),
        ("Hvað heitir fjallgarðurinn í Suður-Ameríku?", ["Andesfjöll"]),
        ("Hvað heitir fjallgarðurinn í Norður-Afríku?", ["Atlas"]),
        ("Á hvaða heimsálfu er Brasilía?", ["Suður-Ameríka"]),
        ("Á hvaða heimsálfu er Ástralía?", ["Eyjaálfa"]),
        ("Hvað heitir minnsta land í heimi?", ["Vatíkanið"]),
        ("Hvað heitir þéttbýlasta land í heimi?", ["Mónakó"]),
        ("Hvaða land hefur lengsta strandlínu í heimi?", ["Kanada"]),
        ("Hvaða heimsálfa er kaldust?", ["Suðurskautslandið"]),
        ("Hvaða heimsálfa er þurrasta?", ["Suðurskautslandið"]),
        ("Hversu margar lönd eru í Afríku?", ["54"]),
        ("Hvaða land er stærst í Suður-Ameríku?", ["Brasilía"]),
        ("Hvaða land er stærst í Afríku?", ["Algeirsland"]),
        ("Hvaða land er stærst í Asíu?", ["Rússland"]),
        ("Hvaða land hefur flesta íbúa í Afríku?", ["Nígeríu"]),
        ("Hvaða land liggur á milli Frakklands og Spánar?", ["Andorra"]),
        ("Hvaða land er á milli Indlands og Kína?", ["Nepal"]),
    ],

    4: [
        ("Hvenær hófst fyrri heimsstyrjöldin?", ["1914"]),
        ("Hvenær lauk fyrri heimsstyrjöldinni?", ["1918"]),
        ("Hvenær hófst seinni heimsstyrjöldin?", ["1939"]),
        ("Hvenær lauk seinni heimsstyrjöldinni?", ["1945"]),
        ("Hvaða land réðst á Pólland 1939?", ["Þýskaland"]),
        ("Hvenær var D-dagurinn í Normandí?", ["1944"]),
        ("Hvaða borg var fyrst sprengd með kjarnorkusprengju?", ["Hiroshima"]),
        ("Hvað hét leiðtogi Sovétríkjanna í seinni heimsstyrjöldinni?", ["Stalín"]),
        ("Hvað hét hermenn Þýskalands í seinni heimsstyrjöldinni?", ["Nasístar"]),
        ("Hvaða land réðst á Pearl Harbor 1941?", ["Japan"]),
        ("Hvenær féll Vestur-Rómaveldið?", ["476"]),
        ("Hvað hét þekktastur keisari Rómaveldis?", ["Ágústus"]),
        ("Hvenær var Magna Carta undirrituð?", ["1215"]),
        ("Hvað hét landvinningamaður sem sigraði Mexíkó?", ["Cortés"]),
        ("Hvenær hófust krossferðirnar?", ["1096"]),
        ("Hvað hét keisari Franklandi um 800?", ["Karl mikli"]),
        ("Hvað hét uppfinningamaður prentpressunnar?", ["Gutenberg"]),
        ("Hvenær uppgötvaði Kólumbus Ameríku?", ["1492"]),
        ("Hvenær fór Leifur Eiríksson til Ameríku?", ["1000"]),
        ("Hvað hét móðir Jesú Krists?", ["María"]),
        ("Hvenær var franska byltingin?", ["1789"]),
        ("Hvað hét konungur Frakklands sem var höfðaður 1793?", ["Lúðvík"]),
        ("Hvað hét fyrsti forseti Bandaríkjanna?", ["Washington"]),
        ("Hvenær var rússneska byltingin?", ["1917"]),
        ("Hvað hét leiðtogi bolsévíkanna?", ["Lenín"]),
        ("Hvenær féll Berlínarmúrinn?", ["1989"]),
        ("Hvenær leystust Sovétríkin upp?", ["1991"]),
        ("Hvað hét fyrsti landnámsmaður Íslands?", ["Ingólfur"]),
        ("Hvenær tók Ísland kristni?", ["1000"]),
        ("Hvað hét biskupssetið á Íslandi á miðöldum?", ["Skálholt"]),
        ("Hvenær varð Ísland hluti af Danaveldi?", ["1380"]),
        ("Hvað hét þekktastur skáld Íslands á miðöldum?", ["Snorri"]),
        ("Hvað hét fyrsti forseti Íslands?", ["Sveinn"]),
        ("Hvað hét fyrsti maðurinn á tunglið?", ["Armstrong"]),
        ("Hvað hét leiðtogi Kína sem stofnaði lýðveldið?", ["Mao"]),
        ("Hvað hét Suður-Afríkumaður sem barðist gegn Apartheid?", ["Mandela"]),
        ("Hvað hét forseti Bandaríkjanna sem var myrtur 1963?", ["Kennedy"]),
        ("Hvað hét fyrsti gervitungl jarðarinnar?", ["Sputnik"]),
        ("Hvað hét þekktasta leikrit Shakespeares?", ["Hamlet"]),
        ("Hvað hét þekktasta ópera Mozarts?", ["Töfraflauturinn"]),
        ("Hvað hét forseti Bandaríkjanna sem afnam þrælahald?", ["Lincoln"]),
        ("Hvað hét leiðtogi sem sameinaði Mongólaveldi?", ["Djingis Khan", "Genghis Khan"]),
        ("Hvað hét fyrsti keisari Kína?", ["Qin Shi Huang"]),
        ("Hvað hét faraó sem reisti stærsta pýramíðann?", ["Kúfú"]),
        ("Hvað hét Portúgalski landvinningamaðurinn sem fór til Indlands?", ["Vasco da Gama"]),
        ("Hvað hét þekktastur Víkingur sem byggði Grænland?", ["Eiríkur rauði"]),
        ("Hvað hét Grikkur sem uppgötvaði þyngdarlögmálið í vatni?", ["Arkímedes"]),
        ("Hvað hét heimspekingur sem kenndi Alexanders mikla?", ["Aristóteles"]),
        ("Hvað hét Egyptneska drottningin sem átti samband við Júlíus Cæsar?", ["Kleopatra"]),
        ("Hvað hét leiðtogi Húnaveldi sem réðst á Evrópu?", ["Attila"]),
        ("Hvað hét Azteka-leiðtogi þegar Cortés kom?", ["Moctezuma"]),
        ("Hvað hét leiðtogi sem stofnaði Zulu-veldi?", ["Shaka"]),
        ("Hvað hét síðasti keisari Kína?", ["Puyi"]),
    ],

    5: [
        ("Hvað heitir frumefni með tákn Au?", ["Gull"]),
        ("Hvað heitir frumefni með tákn Fe?", ["Járn"]),
        ("Hvað heitir frumefni með tákn Ag?", ["Silfur"]),
        ("Hvað heitir frumefni með tákn Na?", ["Natríum"]),
        ("Hvað heitir frumefni með tákn O?", ["Súrefni"]),
        ("Hvað heitir frumefni með tákn H?", ["Vetni"]),
        ("Hvað heitir frumefni með tákn C?", ["Kolefni"]),
        ("Hversu margar frumefni eru í frumefnatöflunni?", ["118"]),
        ("Hvað heitir minnsta eining lífs?", ["Fruma"]),
        ("Hvað heitir kenning Einsteins um tíma og rúm?", ["Afstæðiskenning"]),
        ("Hversu hratt ferðast ljós?", ["300000"]),
        ("Hvað er ferningsrót af 256?", ["16"]),
        ("Hvað er 13 x 13?", ["169"]),
        ("Hvað er 17 x 17?", ["289"]),
        ("Hvað er 2 í þriðja veldi?", ["8"]),
        ("Hvað er 3 í fjórða veldi?", ["81"]),
        ("Hvað er 1000 / 25?", ["40"]),
        ("Hvað er 15% af 300?", ["45"]),
        ("Hvað er 7 x 9?", ["63"]),
        ("Hvað er 144 / 9?", ["16"]),
        ("Hvað er π að næstu heiltölu?", ["3"]),
        ("Hvað hét hljómsveit með Mick Jagger?", ["Rolling Stones"]),
        ("Hvað hét hljómsveit með Kurt Cobain?", ["Nirvana"]),
        ("Hvaða land er Bob Marley frá?", ["Jamaíka"]),
        ("Hvað heitir þekktasta lag Michael Jacksons?", ["Thriller"]),
        ("Hvað hét hljómsveit Bono?", ["U2"]),
        ("Hvað heitir þekktasta lag Eagles?", ["Hotel California"]),
        ("Hvað heitir þekktasta lag Björkur?", ["Human Behaviour"]),
        ("Hvað heitir leikari sem lék Forrest Gump?", ["Hanks"]),
        ("Hvað heitir leikstjóri Star Wars?", ["Lucas"]),
        ("Hvað hét leikari sem lék Neo í Matrix?", ["Reeves"]),
        ("Hvað hét leikari sem lék Joker 2019?", ["Phoenix"]),
        ("Hvað hét leikstjóri Schindlers lista?", ["Spielberg"]),
        ("Hvað heitir þekktastur knattspyrnumaður allra tíma?", ["Pelé", "Pele"]),
        ("Hvaða lið vann Champions League 2022?", ["Real Madrid"]),
        ("Hvað heitir þekktastur körfuboltamaður allra tíma?", ["Jordan"]),
        ("Hvaða ár vann Ísland á EM í knattspyrnu?", ["2016"]),
        ("Hvað heitir hraðastur maður í heimi?", ["Bolt"]),
        ("Hvaða land hefur unnið flest heimsmót í knattspyrnu?", ["Brasilía"]),
        ("Hvað heitir þekktastur tennismaður allra tíma?", ["Federer"]),
        ("Hversu margar gull vann Usain Bolt í ólympíuleikunum?", ["8"]),
        ("Hvað hét höfundur Sjálfstætt fólk?", ["Laxness"]),
        ("Hvaða ár fékk Laxness Nóbelsverðlaunin?", ["1955"]),
        ("Hvað hét höfundur 1984?", ["Orwell"]),
        ("Hvað hét höfundur Don Quixote?", ["Cervantes"]),
        ("Hvað hét höfundur Faust?", ["Goethe"]),
        ("Hvað heitir þekktasta verk Kafkas?", ["Umbreytingin"]),
        ("Hvenær var NATO stofnað?", ["1949"]),
        ("Hvenær var Sameinuðu þjóðirnar stofnaðar?", ["1945"]),
        ("Hvenær var Evrópusambandið stofnað?", ["1993"]),
        ("Hvað heitir þing Bretlands?", ["Parliament"]),
        ("Hvenær var þjóðréttindi sett fram í Bandaríkjunum?", ["1791"]),
        ("Hvenær gekk Ísland í EES?", ["1994"]),
        ("Hvað hét leikstjóri Pulp Fiction?", ["Tarantino"]),
        ("Hvað hét leikari sem lék Hannibal Lecter?", ["Hopkins"]),
        ("Hvað hét leikstjóri 2001: A Space Odyssey?", ["Kubrick"]),
        ("Hvað hét leikari sem lék Tyler Durden í Fight Club?", ["Pitt"]),
        ("Hvað hét höfundur sem skrifaði Fight Club?", ["Palahniuk"]),
        ("Hvað heitir þekktastur stígvélamaður allra tíma?", ["Ali"]),
        ("Hvað heitir þekktastur golfspilar allra tíma?", ["Woods"]),
        ("Hvað heitir þekktastur sundmaður allra tíma?", ["Phelps"]),
        ("Hvaða ár varð Brasilía heimsmeistari í knattspyrnu í fyrsta sinn?", ["1958"]),
        ("Hvað heitir þekktastur skíðamaður allra tíma?", ["Stenmark"]),
        ("Hversu margar gull vann Michael Phelps alls í ólympíuleikunum?", ["23"]),
        ("Hvað heitir lengsta hjólreiðakeppni í heimi?", ["Tour de France"]),
    ],

    6: [
        ("Hvað heitir höfuðborg Kazakstan?", ["Astana"]),
        ("Hvað heitir höfuðborg Úsbekistan?", ["Tasjkent"]),
        ("Hvað heitir höfuðborg Georgíu?", ["Tbilísí"]),
        ("Hvað heitir höfuðborg Armeníu?", ["Jerevan"]),
        ("Hvað heitir höfuðborg Aserbaídsjan?", ["Bakú"]),
        ("Hvað heitir höfuðborg Túrkmenistan?", ["Asjgabat"]),
        ("Hvað heitir höfuðborg Kirgistar?", ["Bisjkek"]),
        ("Hvað heitir höfuðborg Tadsjistar?", ["Dusjanbe"]),
        ("Hvað heitir höfuðborg Líbanons?", ["Beirút"]),
        ("Hvað heitir höfuðborg Sýrlands?", ["Damaskus"]),
        ("Hvað heitir höfuðborg Jórdaníu?", ["Amman"]),
        ("Hvað heitir höfuðborg Ísrael?", ["Jerúsalem"]),
        ("Hvað heitir höfuðborg Óman?", ["Maskat"]),
        ("Hvað heitir höfuðborg Jemen?", ["Sanaa"]),
        ("Hvað heitir höfuðborg Katar?", ["Doha"]),
        ("Hvað hét konungur Englands sem undirritaði Magna Carta?", ["Jón"]),
        ("Hvenær var Konstantínópel tekin af Tyrkjum?", ["1453"]),
        ("Hvað hét fyrsti Rússneski Tsar?", ["Ívan"]),
        ("Hvað hét leiðtogi Mongólanna?", ["Djingis Khan", "Genghis Khan"]),
        ("Hvað hét keisari Rússlands sem var myrtur 1918?", ["Níkolás"]),
        ("Hvað heitir frumefni með tákn K?", ["Kalíum"]),
        ("Hvað heitir frumefni með tákn Pb?", ["Blý"]),
        ("Hvað heitir frumefni með tákn Hg?", ["Kvikasilfur"]),
        ("Hvað heitir frumefni með tákn Cu?", ["Kopar"]),
        ("Hvað heitir frumefni með tákn N?", ["Nitur"]),
        ("Hversu margar krómósómar eru í mannslíkamanum?", ["46"]),
        ("Hvað heitir hlutfallið milli massa og rúmmáls?", ["Þéttleiki"]),
        ("Hversu margar kílómetrar er að miðju jarðarinnar?", ["6371"]),
        ("Hvað heitir stærsta þekkt svartur hola?", ["TON618"]),
        ("Hvað er 19 x 19?", ["361"]),
        ("Hvað er ferningsrót af 529?", ["23"]),
        ("Hvað er 2 í tíunda veldi?", ["1024"]),
        ("Hvað er 7 í þriðja veldi?", ["343"]),
        ("Hvað er 1234 + 5678?", ["6912"]),
        ("Hvað er 33% af 900?", ["297"]),
        ("Hvað er 144 x 144?", ["20736"]),
        ("Hversu margar gráður eru í þríhyrningi?", ["180"]),
        ("Hversu margar gráður eru í hring?", ["360"]),
        ("Hvað hét hljómsveit David Bowie?", ["Spiders from Mars"]),
        ("Hvað heitir þekktasta lag Pink Floyd?", ["Comfortably Numb"]),
        ("Hvað hét hljómsveit Ozzy Osbourne?", ["Black Sabbath"]),
        ("Hvað heitir þekktasta lag Radiohead?", ["Creep"]),
        ("Hvað heitir þekktasta lag Johnny Cash?", ["Ring of Fire"]),
        ("Hvað hét leikstjóri Citizen Kane?", ["Welles"]),
        ("Hvað hét leikstjóri Apocalypse Now?", ["Coppola"]),
        ("Hvað hét leikari sem lék í Raging Bull?", ["De Niro"]),
        ("Hvað hét leikstjóri Vertigo?", ["Hitchcock"]),
        ("Hvað hét leikstjóri Rashomon?", ["Kurosawa"]),
        ("Hvaða ár vann Muhammad Ali WBC titilinn í fyrsta sinn?", ["1964"]),
        ("Hversu margar leikir vann Federer í Grand Slam?", ["20"]),
        ("Hvaða ár vann Brasilía heimsmót í fimmta sinn?", ["2002"]),
        ("Hvað heitir þekktastur íslenskur knattspyrnumaður?", ["Sigurdsson", "Gylfi Sigurdsson"]),
        ("Hversu margar félög eru í efsta deild í knattspyrnu á Íslandi?", ["12"]),
        ("Hvað heitir stærsta knattspyrnuleikvöllur á Íslandi?", ["Laugardalsvöllur"]),
        ("Hvað heitir þekktastur íslenskur krossfitari?", ["Björnsson", "Hafþór Björnsson"]),
    ],

    7: [
        ("Hvað heitir höfuðborg Máritaníu?", ["Nóaksjót"]),
        ("Hvað heitir höfuðborg Mósambík?", ["Mapútó"]),
        ("Hvað heitir höfuðborg Madagaskar?", ["Antananarivo"]),
        ("Hvað heitir höfuðborg Súdan?", ["Kartúm"]),
        ("Hvað heitir höfuðborg Líbíu?", ["Trípólí"]),
        ("Hvað heitir höfuðborg Túnis?", ["Túnis"]),
        ("Hvað heitir höfuðborg Sómalíu?", ["Mogadísú"]),
        ("Hvað heitir höfuðborg Erítreu?", ["Asmara"]),
        ("Hvað heitir höfuðborg Kamerún?", ["Jaunde"]),
        ("Hvað heitir höfuðborg Senegal?", ["Dakar"]),
        ("Hvað heitir höfuðborg Simbabve?", ["Harare"]),
        ("Hvað heitir höfuðborg Zambia?", ["Lúsaká"]),
        ("Hvað heitir höfuðborg Botsvana?", ["Gaborone"]),
        ("Hvað heitir höfuðborg Namibíu?", ["Windhuk"]),
        ("Hvað heitir höfuðborg Kongó?", ["Kinshasa"]),
        ("Hvað hét keisari sem sigraði í Orrustunni við Actium 31 f.Kr.?", ["Ágústus"]),
        ("Hvað hét leiðtogi sem stofnaði Ottómanaveldi?", ["Osman"]),
        ("Hvað hét faraó sem reisti stærsta pýramíðann?", ["Kúfú"]),
        ("Hvenær var Orrusta við Hastings?", ["1066"]),
        ("Hvað hét Mongólski leiðtogi sem réðst á Evrópu 1241?", ["Batu Khan"]),
        ("Hvað hét Portúgalski landvinningamaðurinn sem fór til Indlands 1498?", ["Vasco da Gama"]),
        ("Hvenær var Versailles-sáttmálinn undirritaður?", ["1919"]),
        ("Hvað heitir lögmál sem lýsir sambandi þrýstings og rúmmáls gass?", ["Boyle"]),
        ("Hvað heitir eining orku í SI-kerfinu?", ["Joule"]),
        ("Hvað heitir eining hita í SI-kerfinu?", ["Kelvin"]),
        ("Hvað heitir eining rafsegulkrafts?", ["Tesla"]),
        ("Hvað heitir frumeind sem ber neikvæða hleðslu?", ["Rafeindir"]),
        ("Hvað heitir lögmál um varðveislu orku?", ["Varðveislulögmálið"]),
        ("Hvað heitir frumeind sem ber jákvæða hleðslu?", ["Róteind"]),
        ("Hvað heitir frumeind án hleðslu?", ["Niftein"]),
        ("Hvað er 23 x 23?", ["529"]),
        ("Hvað er ferningsrót af 1764?", ["42"]),
        ("Hvað er 2 í fimmtánda veldi?", ["32768"]),
        ("Hvað er 999 x 999?", ["998001"]),
        ("Hvað er summa hornanna í fimmhyrningi?", ["540"]),
        ("Hvað er summa hornanna í sexhyrningi?", ["720"]),
        ("Hversu margar prímtölur eru minni en 20?", ["8"]),
        ("Hvað er 13 í þriðja veldi?", ["2197"]),
        ("Hvað hét hljómsveit sem Jim Morrison var í?", ["The Doors"]),
        ("Hvað hét hljómsveit Sting?", ["The Police"]),
        ("Hvað heitir þekktasta lag Joy Division?", ["Love Will Tear Us Apart"]),
        ("Hvað hét hljómsveit sem Robert Plant var í?", ["Led Zeppelin"]),
        ("Hvaða ár gaf Pink Floyd út Dark Side of the Moon?", ["1973"]),
        ("Hvað hét hljómsveit þar sem Ian Curtis var söngvari?", ["Joy Division"]),
        ("Hvaða ár gaf The Clash út London Calling?", ["1979"]),
        ("Hvað hét leikstjóri The Godfather?", ["Coppola"]),
        ("Hvaða ár kom Taxi Driver út?", ["1976"]),
        ("Hvaða ár kom Chinatown út?", ["1974"]),
        ("Hvaða ár kom Rashomon út?", ["1950"]),
        ("Hvaða ár vann Brasilía heimsmót í fimmta sinn?", ["2002"]),
        ("Hversu margar gull vann Michael Phelps alls í ólympíuleikunum?", ["23"]),
        ("Hvað heitir lengsta hjólreiðakeppni í heimi?", ["Tour de France"]),
        ("Hvaða ár hófst fyrsta Formula 1 keppnin?", ["1950"]),
    ],

    8: [
        ("Hvað heitir frumefni með tákn W?", ["Wolfram"]),
        ("Hvað heitir frumefni með tákn Pt?", ["Platína"]),
        ("Hvað heitir frumefni með tákn Ti?", ["Títan"]),
        ("Hvað heitir frumefni með tákn Mn?", ["Mangan"]),
        ("Hvað heitir frumefni með tákn Cr?", ["Króm"]),
        ("Hvað heitir frumefni með tákn Zn?", ["Sink"]),
        ("Hvað heitir frumefni með tákn Ni?", ["Nikkel"]),
        ("Hvað heitir frumefni með tákn Co?", ["Kóbalt"]),
        ("Hvað heitir frumefni með tákn Li?", ["Litíum"]),
        ("Hvað heitir frumefni með tákn Be?", ["Beryllíum"]),
        ("Hvað heitir fyrsta lag jarðar?", ["Jarðskorpa"]),
        ("Hvað heitir heitt lag í miðju jarðar?", ["Kjarni"]),
        ("Hvað heitir lögmál um varðveislu massa?", ["Lavoisier"]),
        ("Hversu margar litir eru í litrófi sólarljóss?", ["7"]),
        ("Hvað heitir höfuðborg Burúndí?", ["Gitega"]),
        ("Hvað heitir höfuðborg Rúanda?", ["Kigali"]),
        ("Hvað heitir höfuðborg Úganda?", ["Kampala"]),
        ("Hvað heitir höfuðborg Malawi?", ["Lilongwe"]),
        ("Hvað heitir höfuðborg Sierra Leone?", ["Freetown"]),
        ("Hvað heitir höfuðborg Libería?", ["Monrovia"]),
        ("Hvað heitir höfuðborg Gíneu?", ["Conakry"]),
        ("Hvað heitir höfuðborg Tóga?", ["Lomé"]),
        ("Hvað heitir höfuðborg Benín?", ["Porto-Novo"]),
        ("Hvað heitir höfuðborg Níger?", ["Niamey"]),
        ("Hvað heitir höfuðborg Máli?", ["Bamako"]),
        ("Hvað heitir höfuðborg Búrkína Fasó?", ["Ouagadougou"]),
        ("Hvað heitir höfuðborg Kap Verde?", ["Praia"]),
        ("Hvað heitir höfuðborg Gabon?", ["Libreville"]),
        ("Hvað er næsta prímtala á eftir 97?", ["101"]),
        ("Hvað er 1 + 2 + 3 + ... + 100?", ["5050"]),
        ("Hversu margar hliðar hefur dódekahedral?", ["12"]),
        ("Hversu margar hornpunktar hefur teningur?", ["8"]),
        ("Hvað heitir tala sem er deilanleg með öllum tölum 1-10?", ["2520"]),
        ("Hversu margar prímtölur eru á milli 1 og 50?", ["15"]),
        ("Hvað er 111 x 111?", ["12321"]),
        ("Hvað er ferningsrót af 2025?", ["45"]),
        ("Hvað hét hljómsveit þar sem Morrissey var söngvari?", ["The Smiths"]),
        ("Hvað heitir þekktasta lag Pixies?", ["Where Is My Mind"]),
        ("Hvað hét hljómsveit þar sem Syd Barrett var?", ["Pink Floyd"]),
        ("Hvað heitir þekktasta lag The Velvet Underground?", ["Heroin"]),
        ("Hvað hét höfundur Ulysses?", ["Joyce"]),
        ("Hvað hét höfundur Crime and Punishment?", ["Dostojevski"]),
        ("Hvað hét höfundur One Hundred Years of Solitude?", ["García Márquez"]),
        ("Hvað hét höfundur The Trial?", ["Kafka"]),
        ("Hvað hét höfundur Moby Dick?", ["Melville"]),
        ("Hvað hét höfundur Anna Karenina?", ["Tolstói"]),
        ("Hvað hét höfundur Brave New World?", ["Huxley"]),
        ("Hvað hét höfundur Catch-22?", ["Heller"]),
        ("Hvað hét höfundur Lolita?", ["Nabokov"]),
        ("Hvað hét leikstjóri sem gerði 8½?", ["Fellini"]),
        ("Hvað hét leikstjóri sem gerði The Seventh Seal?", ["Bergman"]),
        ("Hvað heitir stærsta íþróttasamband á Íslandi?", ["ÍSÍ"]),
        ("Hvað heitir stærsta knattspyrnuleikvöllur á Íslandi?", ["Laugardalsvöllur"]),
    ],

    9: [
        ("Hvað heitir lögmál sem lýsir dreifingu rafeinda í frumeind?", ["Pauli"]),
        ("Hvað heitir eining ljósstyrks í SI?", ["Kandela"]),
        ("Hvað heitir eining magns efnis í SI?", ["Mól"]),
        ("Hvað heitir þungustu gerð kvarks?", ["Top"]),
        ("Hvað heitir lögmál um þrýsting vökva?", ["Pascal"]),
        ("Hvað heitir lögmál um rafmagnsspennu og straum?", ["Ohm"]),
        ("Hvað heitir fyrirbæri þegar ljós beygist í kring um þungt hlut?", ["Ljósbeyging"]),
        ("Hvað heitir frumefni með atómnúmer 79?", ["Gull"]),
        ("Hvað heitir frumefni með atómnúmer 82?", ["Blý"]),
        ("Hvað heitir höfuðborg Mikrónesíu?", ["Palikir"]),
        ("Hvað heitir höfuðborg Tonga?", ["Nukualofa"]),
        ("Hvað heitir höfuðborg Samóa?", ["Apia"]),
        ("Hvað heitir höfuðborg Vanuatú?", ["Port Vila"]),
        ("Hvað heitir höfuðborg Salómoneyja?", ["Honiara"]),
        ("Hvað heitir höfuðborg Kíribatí?", ["Tarawa"]),
        ("Hvað heitir höfuðborg Lesótó?", ["Maseru"]),
        ("Hvað heitir höfuðborg Djíbútí?", ["Djíbútí"]),
        ("Hvað heitir höfuðborg Seychelles?", ["Victoria"]),
        ("Hvað heitir höfuðborg Máritíus?", ["Port Louis"]),
        ("Hvað hét Grikkur sem reiknaði ummál jarðar?", ["Eratosþenes"]),
        ("Hvað hét Rómverskur stjórnmálamaður sem var myrtur á Ides of March?", ["Cæsar"]),
        ("Hvað hét keisari sem byggði Hagia Sophia?", ["Justinianus"]),
        ("Hvað hét Persneska keisarinn sem réðst á Grikkland?", ["Xerxes"]),
        ("Hvað hét leiðtogi sem sameinaði Japan á 16. öld?", ["Hideyoshi"]),
        ("Hvað hét síðasti keisari Rómaveldis að austan?", ["Konstantín"]),
        ("Hvað hét Spænski landvinningamaðurinn sem sigraði Inkaveldið?", ["Pizarro"]),
        ("Hvað er summa allra hornanna í tígul?", ["360"]),
        ("Hvað er 7 í fjórða veldi?", ["2401"]),
        ("Hvað er ferningsrót af 7921?", ["89"]),
        ("Hversu margar hliðar hefur ikosahedron?", ["20"]),
        ("Hvað er 42 x 42?", ["1764"]),
        ("Hvað er 2 í tuttugasta veldi?", ["1048576"]),
        ("Hvað hét hljómsveit Mark E. Smith?", ["The Fall"]),
        ("Hvað hét hljómsveit þar sem Scott Walker var?", ["Walker Brothers"]),
        ("Hvað heitir þekktasta lag Suicide?", ["Ghost Rider"]),
        ("Hvað hét hljómsveit þar sem Robert Wyatt var?", ["Soft Machine"]),
        ("Hvað hét söngvari Wire?", ["Colin Newman"]),
        ("Hvað hét hljómsveit þar sem Ian MacKaye var?", ["Fugazi"]),
        ("Hvað hét höfundur The Stranger?", ["Camus"]),
        ("Hvað hét höfundur Blood Meridian?", ["McCarthy"]),
        ("Hvað hét höfundur Infinite Jest?", ["Wallace"]),
        ("Hvað hét höfundur Gravity's Rainbow?", ["Pynchon"]),
        ("Hvað hét höfundur 2666?", ["Bolaño"]),
        ("Hvað hét höfundur The Tin Drum?", ["Grass"]),
        ("Hvað heitir elsta þing í heimi?", ["Alþingi"]),
        ("Hvað heitir þekktasta saga Snorra Sturlusonar?", ["Heimskringla"]),
        ("Hvað heitir hæsti fjall á Íslandi?", ["Hvannadalshnjúkur"]),
        ("Hvað heitir stærsta þjóðgarðurinn á Íslandi?", ["Vatnajökulsþjóðgarður"]),
        ("Hvað heitir þekktasta gata í Reykjavík?", ["Laugavegur"]),
        ("Hvað heitir stærsta hverfi í Reykjavík?", ["Breiðholt"]),
        ("Hvað heitir lengsti fljót á Íslandi?", ["Þjórsá"]),
        ("Hvað heitir dýpsti fjörður á Íslandi?", ["Ísafjarðardjúp"]),
    ],

    10: [
        ("Hvað heitir lögmál sem lýsir dreifingu svartra líkama geislunar?", ["Planck"]),
        ("Hvað heitir eind sem ber litskyn í skammtafræði?", ["Gluon"]),
        ("Hvað heitir frumefni með atómnúmer 92?", ["Úraníum"]),
        ("Hvað heitir frumefni með atómnúmer 88?", ["Radíum"]),
        ("Hvað heitir frumefni með atómnúmer 78?", ["Platína"]),
        ("Hvað heitir kenning sem sameinar skammtafræði og sérstæðiskenninguna?", ["Strengjafræði"]),
        ("Hvað heitir lögmál um rafsegulbylgjur?", ["Maxwell"]),
        ("Hvað heitir höfuðborg Naúrú?", ["Yaren"]),
        ("Hvað heitir höfuðborg Túvalú?", ["Funafuti"]),
        ("Hvað heitir höfuðborg Wallis og Fútúna?", ["Mata-Utu"]),
        ("Hvað heitir höfuðborg Pitcairn?", ["Adamstown"]),
        ("Hvað heitir höfuðborg Svalbarda?", ["Longyearbyen"]),
        ("Hvað heitir höfuðborg Falklandseyja?", ["Stanley"]),
        ("Hvað heitir höfuðborg Tristan da Cunha?", ["Edinburgh"]),
        ("Hvað heitir höfuðborg Montserrat?", ["Plymouth"]),
        ("Hvað heitir höfuðborg Anguilla?", ["The Valley"]),
        ("Hvað hét Grikkur sem skrifaði Ilíonskviðu?", ["Hómer"]),
        ("Hvað hét fyrsti keisari Kína að nafni?", ["Qin Shi Huang"]),
        ("Hvað hét Arabiskur landvinningamaður sem réðst á Spán?", ["Tariq ibn Ziyad"]),
        ("Hvað hét Byzantínskur keisari sem samdi Justinianus-löggjöfina?", ["Justinianus"]),
        ("Hvað hét Mongólskur Khan sem réðst á Bagdad?", ["Hulagu"]),
        ("Hvað er 997 x 997?", ["994009"]),
        ("Hvað er ferningsrót af 15129?", ["123"]),
        ("Hvað er 17 í þriðja veldi?", ["4913"]),
        ("Hversu margar prímtölur eru á milli 50 og 100?", ["10"]),
        ("Hvað er 1 + 1/2 + 1/4 + 1/8 + ... (óendanlegt)?", ["2"]),
        ("Hvað er 999 x 1001?", ["999999"]),
        ("Hvað er summa allra hornanna í tíhyrningi?", ["1440"]),
        ("Hvað er 2 í þrítugasta veldi?", ["1073741824"]),
        ("Hvað er 101 x 99?", ["9999"]),
        ("Hvað hét hljómsveit þar sem Kevin Shields var?", ["My Bloody Valentine"]),
        ("Hvað heitir þekktasta lag Swans?", ["The Seer"]),
        ("Hvað hét hljómsveit þar sem Thurston Moore var?", ["Sonic Youth"]),
        ("Hvað hét söngvari Dead Can Dance?", ["Lisa Gerrard"]),
        ("Hvað hét hljómsveit þar sem Peter Murphy var?", ["Bauhaus"]),
        ("Hvað heitir þekktasta lag Slint?", ["Washer"]),
        ("Hvað heitir þekktasta lag Current 93?", ["All the Pretty Little Horses"]),
        ("Hvað hét höfundur The Waves?", ["Woolf"]),
        ("Hvað hét höfundur The Sound and the Fury?", ["Faulkner"]),
        ("Hvað hét höfundur Pedro Páramo?", ["Rulfo"]),
        ("Hvað hét höfundur The Makioka Sisters?", ["Tanizaki"]),
        ("Hvað hét höfundur The Master and Margarita?", ["Bulgakov"]),
        ("Hvað hét höfundur Austerlitz?", ["Sebald"]),
        ("Hvað hét höfundur Ficciones?", ["Borges"]),
        ("Hvað hét höfundur The Unconsoled?", ["Ishiguro"]),
        ("Hvað heitir elsta kvikmyndahús á Íslandi?", ["Gamla Bíó"]),
        ("Hvað heitir kaldasti mánuðurinn á Íslandi að meðaltali?", ["Janúar"]),
        ("Hvað heitir stærsta náttúrulegt lón á Íslandi?", ["Mývatn"]),
        ("Hvað hét þekktastur skáld Íslendingasagna?", ["Snorri"]),
        ("Hvað hét fyrsti biskup Íslands?", ["Ísleifur"]),
        ("Hvað heitir elsta kirkja á Íslandi?", ["Þingvallakirkja"]),
    ],
}

def get_questions(level):
    qs = QUESTIONS.get(level, None)
    if not qs:
        for lvl in range(level, 0, -1):
            if QUESTIONS.get(lvl):
                qs = QUESTIONS[lvl]
                break
    result = qs.copy()
    random.shuffle(result)
    return result
